<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-5PMM0HN" name="week4groups.TC005_DuplicateLead" tests="1" failures="0" timestamp="6 Jan 2019 21:41:35 GMT" time="0.000" errors="1">
  <testcase name="Duplicate" time="0.000" classname="week4groups.TC005_DuplicateLead">
    <error type="java.lang.Throwable" message="Method TC005_DuplicateLead.Duplicate(java.lang.String)[pri:0, instance:week4groups.TC005_DuplicateLead@17996a0] depends on not successfully finished methods in group &quot;sanity&quot;">
      <![CDATA[java.lang.Throwable: Method TC005_DuplicateLead.Duplicate(java.lang.String)[pri:0, instance:week4groups.TC005_DuplicateLead@17996a0] depends on not successfully finished methods in group "sanity"
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1033)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
	at org.testng.TestNG.run(TestNG.java:1018)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:112)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:205)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:176)
]]>
    </error>
  </testcase> <!-- Duplicate -->
</testsuite> <!-- week4groups.TC005_DuplicateLead -->
